name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  # -------------------------------------------------------------
  # Using GitHub's API is not supported for push events
  # -------------------------------------------------------------
  #
  # ----------------------------------------------------------------------------------------------
  # Using local .git history
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch
  # ----------------------------------------------------------------------------------------------
  PRValidation:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      VALIDATION_OUTPUT: ${{ steps.runValidation.outputs.VALIDATION_OUTPUT }}
    steps:
      - run: echo "Check PR is Valid"

      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46

      - name: install requirements
        run: pip install -r requirements.txt

      - id: runValidation
        run: python scripts/validate_pr.py ${{ github.event.pull_request.user.login }} ${{ steps.changed-files.outputs.all_changed_files }}

  changed_files:
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
      - name: View PR author
        run: echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
  AddComment:
    needs: PRValidation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - env:
          VALIDATION_OUTPUT: ${{needs.PRValidation.outputs.VALIDATION_OUTPUT}}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ${{env.VALIDATION_OUTPUT}}
