name: CI

on:
  pull_request:
jobs:
  # -------------------------------------------------------------
  # Using GitHub's API is not supported for push events
  # -------------------------------------------------------------
  #
  # ----------------------------------------------------------------------------------------------
  # Using local .git history
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch
  # ----------------------------------------------------------------------------------------------
  PRValidation:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      VALIDATION_OUTPUT: ${{ steps.runValidation.outputs.VALIDATION_OUTPUT }}
    steps:
      - run: echo "Check PR is Valid"

      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46

      - name: install requirements
        run: pip install -r requirements.txt

      - id: runValidation
        run: python scripts/validate_pr.py ${{ github.event.pull_request.user.login }} ${{ steps.changed-files.outputs.all_changed_files }}

  AddComment:
    needs: PRValidation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - env:
          VALIDATION_OUTPUT: ${{needs.PRValidation.outputs.VALIDATION_OUTPUT}}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ${{env.VALIDATION_OUTPUT}}
          message-id: uuidgen

  auto-approve:
    needs: PRValidation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
